version: '3.5'
services:
  react:
    build:
      context: ./services/react/
      dockerfile: Dockerfile
    image: react
    container_name: react
    restart: unless-stopped
    volumes:
    #      - ./services/react:/usr/src/app
      - ./services/react:/app:z  # z needed for selinux
      - /app/node_modules
      - /build/client-dev
    env_file: .env
  react-nginx:
    build:
      context: ./services/react-nginx/
      dockerfile: Dockerfile
    image: react-nginx
    container_name: react-nginx
    restart: always
    volumes:
      - ./services/react/build/client-dev/:/client
    env_file: .env
    depends_on:
      - react
  reverseproxy:
    build:
      context: ./services/reverseproxy/
      dockerfile: Dockerfile
    image: reverseproxy
    container_name: reverseproxy
    restart: always
    ports:
      - 80:80 # react app
    depends_on:
      - react
      - react-nginx